### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by qingchunlizhi** [ros-teleop/teleop_twist_keyboard#15]
When I run "rosrun teleop_twist_keyboard teleop_twist_keyboard.py",I get this error:
**File "/opt/ros/melodic/lib/teleop_twist_keyboard/teleop_twist_keyboard.py", line 83
    pub = rospy.Publisher('cmd_vel', Twist, queue_size = 1)
                                                                                             ^
TabError: inconsistent use of tabs and spaces in indentation**

then I replace all the "Tab" to "space" ,it works!!
So, does this code need to be modified?

**Comment by kambic** [comment]
same issue for me, but replacing "Tab" to "space" dont fix error for me. runing ros melodic

**Comment by trainman419** [comment]
That's odd. There were definitely mixed tabs and spaces in that file, but they'd been there for quite a few years, so I'm surprised that this is the first time it's been a problem.

Anyway, this will be fixed in the next release.

**Comment by trainman419** [comment]
The fix for this has been released in version 0.6.2 . Please keep an eye on the [release tag on ROS Discourse](https://discourse.ros.org/tags/release) to see when this reaches the public repositories for your version of ROS.
