### ISSUE TITLE
[Feature request] Publish Twist message at a fixed rate

### ISSUE THREAD

**Issue by drtritm** [ros-teleop/teleop_twist_keyboard#22]
Hello, I am really glad if you have an option that publish the twist message at a fixed rate instead of keeping pushing down the key button

**Comment by trainman419** [comment]
Thanks!

**Comment by trainman419** [comment]
Implemented a repeat rate option in https://github.com/ros-teleop/teleop_twist_keyboard/pull/24 ; please give that a try.

**Comment by drtritm** [comment]
Dear, I tried and saw no difference. Please correct me if I'm wrong

**Comment by trainman419** [comment]
@drtritm did you try with the `_repeat_rate` parameter set? If that parameter is not set, it will default back to the current behavior.

**Comment by drtritm** [comment]
Yes,of course. I even tried it with time out param.nothing changed

**Comment by trainman419** [comment]
That's odd. How did you download and install the updated version?

**Comment by trainman419** [comment]
I've released the changes in #24 ; they should be available in the next sync of your ROS distro.
