### ISSUE TITLE
Robot does not stop on key release

### ISSUE THREAD

**Issue by Timple** [ros-teleop/teleop_twist_keyboard#8]
With other teleop_twist packages, typically releasing the chosen device also stops the movement. 

Take for example the teleop_joy and the spacenav_node.

Can this be implemented to be consistent? I also think that it is the behaviour people expect when using this node.

**Comment by trainman419** [comment]
I'd gladly accept a pull request that implements stopping when a key is released.

The current implementation reads characters from standard input (not keypress events), so it doesn't currently receive a key up event that could be used to implement this. If you know the key repeat rate you might be able to detect when the key is released using a timeout that is  2x or 3x longer than the repeat interval.

**Comment by Timple** [comment]
I briefly looked into this and it is indeed not very trivial to detect a key-up event. Working with the repeat rate as criterion seems best for now. Then I only need to find the repeat interval. 

Little busy at the moment, but I'll try to pick this up.

**Comment by trainman419** [comment]
Implemented in #24 and released to Kinetic, Melodic and Noetic as version 1.0.0 (  https://github.com/ros/rosdistro/pull/25604, https://github.com/ros/rosdistro/pull/25607, https://github.com/ros/rosdistro/pull/25608 )
